@startuml
hide circles

class Cliente{
Id_Cliente
Nome
Email
Password
Morada

}
class Carrinho{
Id_Cliente
Id_Produto
Nome_Produto
Quantidade
Valor

}
class EncomendaDeCliente{
Id_Encomenda
Id_Cliente
Valor_Total

}
class Produto{
Id_Produto
Nome_Produto
Preço

}
class Funcionario{

Id_Funcionario
Nome
Data_Nascimento
Morada
}

class Gerente{

Id_gerente
Nome
Data_Nascimento
Morada

}
Gerente "1" -|> "*" Funcionario : Gere
Funcionario "*" --> "*" EncomendaDeCliente : Gere
Cliente "1"-|> "*"Carrinho : Contém
Cliente "1"-|> "*" EncomendaDeCliente : Realiza
Carrinho "1"-|> "1" EncomendaDeCliente : Necessita
Carrinho "1"--> "*" Produto : Contém
@enduml