@startuml
actor Gerente
participant Sistema

Gerente -> Sistema : Solicita criar produto
Sistema --> Gerente : Pede os dados do produto
Sistema -> Sistema : Cria o produto

alt "Produto criado: true":
    Sistema --> Gerente : Retorna Sucesso
else "Produto criado: false"
    Sistema --> Gerente : Retorna Erro
end
@enduml