@startuml
actor Gerente
participant Sistema

Gerente -> Sistema : Solicita Listar Produtos
Sistema -> Sistema : Verifica se existe produtos

alt "Produtos existentes: true":
    Sistema --> Gerente : Retorna a lista de produtos
else "Produtos existentes: false"
    Sistema --> Gerente : Retorna Erro
end
@enduml