@startuml
actor Gerente
participant Sistema

Gerente -> Sistema : Opção adicionar Funcionário
Sistema --> Gerente : Pede dados do funcionário
Gerente -> Sistema : preenche os dados do funcionário
Sistema -> Sistema : adiciona o novo funcionário

alt "Funcionário adicionado: true":
    Sistema --> Gerente : Retorna Sucesso
else "Funcionário adicionado: false"
    Sistema --> Gerente : Retorna erro
end
@enduml