@startuml
 actor Gerente
 participant Sistema

 Gerente -> Sistema : Solicita Encomenda ao Fornecedor
 Sistema --> Gerente : Apresenta o formulário de encomenda
 Gerente -> Sistema : Submete o formulário
 Sistema -> Sistema : Verifica se está correta a encomenda

 alt "Encomenda correta: true":
     Sistema -> Sistema : Envia para o fornecedor
     Sistema --> Gerente : Retorna sucesso
 else "Encomenda correta: false"
     Sistema --> Gerente : Retorna Erro
 end
@enduml