@startuml
actor Gerente
participant Sistema

Gerente -> Sistema : Solicita listar clientes
Sistema -> Sistema : Verifica se existe clientes

alt "Clientes existentes: true":
    Sistema --> Gerente : Retorna a lista de clientes
else "Clientes existentes: false"
    Sistema --> Gerente : Retorna Erro
end
@enduml