@startuml
actor Gerente
participant Sistema

Gerente -> Sistema : Opção remover Funcionário
Sistema --> Gerente : Pergunta se confirma a remoção
Gerente -> Sistema : Confirma a remoção
Sistema -> Sistema : remove o funcionário
Sistema -> Gerente : exibe mensagem de sucesso

alt "Produto selecionado: true":
    Sistema --> Gerente : Return true
else "Produto selecionado: false"
    Sistema --> Gerente : return failure
end
@enduml